In [3]:
print('hello world')

hello world


In [8]:
import numpy as np

In [20]:
a = np.array([1,2,3])
print(a)
print('array a:{}'.format(a))
print('ndim:',a.ndim)
print('size of array:',a.size)
print('shape of array:',a.shape)
print('data type:',a.dtype)
print('itemsize:',a.itemsize)

[1 2 3]
array a:[1 2 3]
ndim: 1
size of array: 3
shape of array: (3,)
data type: int64
itemsize: 8


In [26]:
b = np.array([[1,2,3],[1,2,3]])
print(b)
print('ndim:',b.ndim)
print('size of array:',b.size)
print('shape of array:',b.shape)
print('data type:',b.dtype)
print('itemsize:',b.itemsize)

[[1 2 3]
 [1 2 3]]
ndim: 2
size of array: 6
shape of array: (2, 3)
data type: int64
itemsize: 8


In [47]:
c = np.array([5,7,6])
d = np.add(a,c)
e = np.subtract(a,c)
print('add',d)
print('sub',e)
print('div',np.divide(a,c))
print('pow',np.power(a,c))
print('multiple',np.multiply(a,c))
print('mod',np.mod(a,c))
print('remainder',np.remainder(a,c))
print('absolute',np.absolute(a,c))

add [6 9 9]
sub [-4 -5 -3]
div [0.2        0.28571429 0.5       ]
pow [  1 128 729]
multiple [ 5 14 18]
mod [1 2 3]
remainder [1 2 3]
absolute [1 2 3]


In [50]:
a = np.array(['sandip','naman','digu'])
print(a)
print('ndim:',a.ndim)
print('size of array:',a.size)
print('shape of array:',a.shape)
print('data type:',a.dtype)
print('itemsize:',a.itemsize)

['sandip' 'naman' 'digu']
ndim: 1
size of array: 3
shape of array: (3,)
data type: <U6
itemsize: 24


In [63]:
ar = np.arange(1,5,0.5)
print(ar)


[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [70]:
a = np.random.random((2,2))
print(a)

[[0.90707307 0.25997148]
 [0.0225364  0.7046009 ]]
